config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  root 'home#top'
  post '/callback' => 'line_bot#callback'

  devise_for :admin_users

  namespace :api, {format: 'json'} do
    namespace :v1 do
      resources :otaku_words, only: [:index, :show]
    end
  end
  resources :categories
  resources :otaku_words
end

app/models/otaku_word.rb
# frozen_string_literal: true

class OtakuWord < ApplicationRecord
  has_many :category_and_otaku_word_relationships
  has_many :categories, through: :category_and_otaku_word_relationships, dependent: :destroy

  accepts_nested_attributes_for :category_and_otaku_word_relationships, allow_destroy: true
end

app/controllers/api/v1/otaku_words_controller.rb
# frozen_string_literal: true

class Api::V1::OtakuWordsController < ApiController
  before_action :set_otaku_word, only: :show

  # ActiveRecordのレコードが見つからなければ404 not foundを応答する
  rescue_from ActiveRecord::RecordNotFound do |_exception|
    render json: { error: '404 not found' }, status: 404
  end

  def index
    otaku_words = OtakuWord.select(:id, :word, :meaning, :description)
    render json: otaku_words
  end

  def show
    render json: @otaku_word
  end

  private

  def set_otaku_word
    @otaku_word = OtakuWord.find(params[:id])
  end
end

app/controllers/otaku_words_controller.rb
class OtakuWordsController < ApplicationController
  before_action :set_otaku_word, only: [:show, :edit, :update, :destroy]

  # GET /otaku_words
  # GET /otaku_words.json
  def index
    @q = OtakuWord.ransack(params[:q])
    @otaku_words = @q.result(distinct: true).order(:created_at)
  end

  # GET /otaku_words/1
  # GET /otaku_words/1.json
  def show; end

  # GET /otaku_words/new
  def new
    @otaku_word = OtakuWord.new
  end

  # GET /otaku_words/1/edit
  def edit; end

  # POST /otaku_words
  # POST /otaku_words.json
  def create
    @otaku_word = OtakuWord.new(otaku_word_params)

    respond_to do |format|
      if @otaku_word.save
        format.html { redirect_to @otaku_word, notice: 'Otaku word was successfully created.' }
        format.json { render :show, status: :created, location: @otaku_word }
      else
        format.html { render :new }
        format.json { render json: @otaku_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /otaku_words/1
  # PATCH/PUT /otaku_words/1.json
  def update
    respond_to do |format|
      if @otaku_word.update(otaku_word_params)
        format.html { redirect_to @otaku_word, notice: 'Otaku word was successfully updated.' }
        format.json { render :show, status: :ok, location: @otaku_word }
      else
        format.html { render :edit }
        format.json { render json: @otaku_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /otaku_words/1
  # DELETE /otaku_words/1.json
  def destroy
    @otaku_word.destroy
    respond_to do |format|
      format.html { redirect_to otaku_words_url, notice: 'Otaku word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_otaku_word
      @otaku_word = OtakuWord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def otaku_word_params
      params.fetch(:otaku_word, {})
    end
end

app/helpers/otaku_words_helper.rb
# frozen_string_literal: true

module OtakuWordsHelper
end

app/views/otaku_words/_form.html.haml
= form_for @otaku_word do |f|
  - if @otaku_word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@otaku_word.errors.count, "error")} prohibited this otaku_word from being saved:"
      %ul
        - @otaku_word.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/otaku_words/_search_form.html.haml
= search_form_for(q) do |f|
  .card.mb-3
    .card-header.bg-dark
      .text-white
        検索フォーム
    .card-body
      .form-row
        .col
          .form-group.mr-md-2
            = f.label :word_cont, 'オタク用語から検索', class: 'text-sm mr-md-2'
            = f.search_field :word_cont, class: 'form-control form-control-sm'
        .col
          .form-group.mr-md-2
            = f.label :meaning_cont, '標準語から検索', class: 'text-sm mr-md-2'
            = f.search_field :meaning_cont, class: 'form-control form-control-sm'
        .col
          .form-group.mr-md-2
            = f.label :categories_id_eq, 'カテゴリー', class: 'text-sm mr-md-2'
            = f.collection_select :categories_id_eq, Category.all, :id, :name, { include_blank: '指定なし' }, { class: 'form-control form-control-sm' }
    .card-footer
      .text-left
        = f.submit'検索', class: 'btn btn-primary'

app/views/otaku_words/edit.html.haml
%h1 Editing otaku_word

= render 'form'

= link_to 'Show', @otaku_word
\|
= link_to 'Back', otaku_words_path

app/views/otaku_words/index.html.haml
.row.justify-content-center
  .col-sm-12.col-md-10.col-lg-8
    .text-center
      .col-12
        = render 'layouts/search_forms', q: @q
      %table.table.table-hover{ border: 2, bordercolor: '#333333', width: '100%' }
        %thead.thead-dark
          %tr
            %th{ style: 'width: 10%'} No.
            %th{ style: 'width: 30%'} オタク語
            %th{ style: 'width: 40%'} 標準語
            %th{ style: 'width: 20%'} カテゴリー
        %tbody.table-primary
          - @otaku_words.each do |otaku_word|
            %tr{ data: { href: otaku_word_path(otaku_word) } }
              %td= otaku_word.id
              %td= otaku_word.word
              %td= otaku_word.meaning
              %td
                %ul
                  - otaku_word.categories.each do |category|
                    %li{ class: category.categories_badge }= category.name

app/views/otaku_words/new.html.haml
%h1 New otaku_word

= render 'form'

= link_to 'Back', otaku_words_path

app/views/otaku_words/show.html.haml
.row.justify-content-center
  .col-sm-12.col-md-10.col-lg-8
    .text-center
      %table.table.table-primary{ border: 2, bordercolor: '#333333' , cellpadding: 5, cellspacing: 0, style: 'table-layout: fixed', width: '100%' }
        %tr
          %td.font-weight-bold.table-dark{ style: 'width: 30%' } No.
          %td= @otaku_word.id
        %tr
          %td.font-weight-bold.table-dark オタク語
          %td= @otaku_word.word
        %tr
          %td.font-weight-bold.table-dark 標準語
          %td{ style: "word-wrap:break-word;" }= @otaku_word.meaning
        %tr
          %td.font-weight-bold.table-dark 解説
          %td{ style: "word-wrap:break-word;" }= @otaku_word.description
        %tr
          %td.font-weight-bold.table-dark カテゴリー
          %td
            %ul
              - @otaku_word.categories.each do |category|
                %li{ class: category.categories_badge }= link_to category.name, category_path(category)
        %tr
          %td.font-weight-bold.table-dark 作成日
          %td= @otaku_word.created_at
        %tr
          %td.font-weight-bold.table-dark 最終更新日
          %td= @otaku_word.updated_at
      = link_to '戻る', otaku_words_path, class: 'btn btn-outline-primary'