config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  root 'home#top'
  post '/callback' => 'line_bot#callback'

  devise_for :admin_users

  namespace :api, {format: 'json'} do
    namespace :v1 do
      resources :otaku_words, only: [:index, :show]
    end
  end
  resources :categories
  resources :otaku_words
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :category_and_otaku_word_relationships
  has_many :otaku_words, through: :category_and_otaku_word_relationships, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.fetch(:category, {})
    end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.row.justify-content-center
  .col-6
    .text-center
      %table.table.table-hover{ border: 2, bordercolor: '#333333', width: '100%' }
        %thead.thead-dark
          %tr
            %th No.
            %th カテゴリー名
            %th 説明
        %tbody.table-success
          - @categories.each do |category|
            %tr{ data: { href: category_path(category) } }
              %td= category.id
              %td= category.name
              %td= category.description

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
.row.justify-content-center
  .col-6
    .text-center
      %table.table.table-success{ border: 2, bordercolor: '#333333' , cellpadding: 5, cellspacing: 0, style: 'table-layout: auto;', width: '50%' }
        %tr
          %td.font-weight-bold.table-dark No.
          %td= @category.id
        %tr
          %td.font-weight-bold.table-dark カテゴリー名
          %td= @category.name
        %tr
          %td.font-weight-bold.table-dark 説明
          %td= @category.description
        %tr
          %td.font-weight-bold.table-dark 作成日
          %td= @category.created_at
        %tr
          %td.font-weight-bold.table-dark 最終更新日
          %td= @category.updated_at

      = link_to '戻る', :back, class: 'btn btn-outline-primary '